version: "3.9"
services:
  mongodb:
    build:
      context: ./mongodb_replica
      args:
        MONGO_VERSION: 7
    ports:
      - "27017:27017"
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_COMMAND: "mongosh"
    restart: always
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
